from pgvector.sqlalchemy import Vector
from sqlalchemy import Computed, Index, String, Text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from database.connection import Base

EMBEDDING_DIM = 768  # BAAI/bge-base-en-v1.5

class Chunk(Base):
    __tablename__ = "chunk"

    id: Mapped[int] = mapped_column(primary_key=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(String, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)

    # sparse half of hybrid search. Generated by Postgres so it can never drift from
    # content — seeding stays a plain add_all() with nothing extra to populate.
    # 'english'::regconfig is spelled out because the 1-arg to_tsvector() reads a
    # session GUC, which makes it non-IMMUTABLE and illegal in a generated column.
    fts: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english'::regconfig, content)", persisted=True),
    )

    __table_args__ = (Index("chunk_fts_idx", "fts", postgresql_using="gin"),)
